### DISCUSSION TITLE
can not run success in docker

### DISCUSSION THREAD

**Discussion by mengluo04** [chevereto/docker#80] [Q&A]
this is my docker-compose.yaml
```yaml
services:
  chevereto:
    image: chevereto/chevereto:latest
    volumes:
      - /volume2/docker/chevereto/storage:/var/www/html/images/
    restart: always
    environment:
      CHEVERETO_DB_HOST: rm-2ze177m4gpq9j2kd7to.mysql.rds.aliyuncs.com
      CHEVERETO_DB_USER: tuchuang
      CHEVERETO_DB_PASS: tuchuang123-
      CHEVERETO_DB_PORT: 3306
      CHEVERETO_DB_NAME: chevereto
      CHEVERETO_ASSET_STORAGE_TYPE: local
      CHEVERETO_ASSET_STORAGE_URL: /images/_assets/
      CHEVERETO_ASSET_STORAGE_BUCKET: /var/www/html/images/_assets/
      CHEVERETO_MAX_POST_SIZE: 2G
      CHEVERETO_MAX_UPLOAD_SIZE: 2G
      CHEVERETO_SERVICING: server
    ports:
      - "10088:80"  # 将主机的 10088 端口映射到容器的 80 端口
```
I visit http://192.168.5.187:10088,I got an error page like this
![image](https://github.com/user-attachments/assets/f9906171-1880-4bec-87ae-d7606039e85b)
