### ISSUE TITLE
Unable to upload Avatar, background image

### ISSUE THREAD

**Issue by rwrr-0644** [Chevereto/docker#16]
![image](https://user-images.githubusercontent.com/51198825/121116150-ac5e6500-c848-11eb-9f28-1884ebdad5e7.png)
No error in upload API response json.
My `content /images/users/*` (in mounted dir) permission is `drwxr-xr-x www-data www-data 4096`, and the image file isn't there after uploading. 
![image](https://user-images.githubusercontent.com/51198825/121116518-43c3b800-c849-11eb-895f-fe637c08f97e.png)

I tried to change their owner group to `root:root`, the upload API (`/json`) will return error message:
![image](https://user-images.githubusercontent.com/51198825/121117202-51c60880-c84a-11eb-8394-6c6730bb42c4.png)

The broken avatar image display path on front: `/content/images/users/7HaC/av_1623091761.jpg`, but there is not thing in `7HaC`.

Q1: What's the correct permission & ownership setting?
Q2: If I want to use S3 Compatible as assets storage, how can I set up the **endpoint**? 
Q3: And I'm not sure if `CHEVERETO_ASSET_STORAGE_ACCOUNT_ID` and `CHEVERETO_ASSET_STORAGE_ACCOUNT_NAME` is necessary? Can I understand as this: all users' avatar and background image will be upload to this S3 storage I set, if not account id or name provided?

Regards.

**Comment by rwrr-0644** [comment]
PS: docker-compose.yml
```yml
version: '3.7'
services:

  mariadb:
    restart: always
    image: mariadb:focal
    networks:
      - internal_network
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxx
      - MYSQL_DATABASE=xxxx
      - MYSQL_USER=xxxx
      - MYSQL_PASSWORD=xxxx
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent"]
    volumes:
      - ./db:/var/lib/mysql

  chevereto:
    restart: always
    image: chevereto/chevereto:3.20-httpd-php
    ports:
      - "780:80"
    networks:
      - external_network
      - internal_network
    environment:
      - CHEVERETO_TAG=latest
      - CHEVERETO_SOFTWARE=xxxx
      - CHEVERETO_LICENSE=xxx
      - CHEVERETO_HOSTNAME=example.com
      - CHEVERETO_DB_HOST=mariadb
      - CHEVERETO_DB_USER=xxxx
      - CHEVERETO_DB_NAME=xxxx
      - CHEVERETO_DB_PASS=xxxxx
      - CHEVERETO_DEBUG_LEVEL=2
      - CHEVERETO_HTTPS=true
    volumes:
      - ./app:/var/www/html

networks:
  external_network:
  internal_network:
    internal: true
```
